# Generated by Django 5.0.6 on 2026-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PRESIDENT', 'Président'), ('SECRETAIRE', 'Secrétaire'), ('TRESORIER', 'Trésorier'), ('DISCIPLINAIRE', 'Responsable disciplinaire'), ('ORGANISATEUR', 'Organisateur'), ('ADMIN', 'Administrateur'), ('SERVANT', 'Servant')], max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['libelle'],
            },
        ),
    ]
