# Generated by Django 5.0.6 on 2026-08-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_seed_ceremoniaire_conseiller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('PRESIDENT', 'Président'), ('SECRETAIRE', 'Secrétaire'), ('TRESORIER', 'Trésorier'), ('DISCIPLINAIRE', 'Responsable disciplinaire'), ('ORGANISATEUR', 'Organisateur'), ('CEREMONIAIRE', 'Cérémoniaire'), ('CONSEILLER', 'Conseiller'), ('ADMIN', 'Administrateur'), ('SERVANT', 'Servant'), ('SUPER_ADMIN', 'Super Admin')], max_length=20, unique=True),
        ),
    ]
