# Generated by Django 5.0.6 on 2026-07-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membre_depuis',
            field=models.DateField(blank=True, help_text="Date d'entrée dans le groupe (ex: 2019)", null=True),
        ),
    ]
