# Generated by Django 5.0.6 on 2026-07-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_membre_depuis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, help_text='Date de naissance', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personne_a_prevenir',
            field=models.CharField(blank=True, help_text='Nom/Prénom du tuteur ou proche', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='membre_depuis',
            field=models.DateField(blank=True, help_text="Date d'intégration dans le groupe", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, help_text='Contact principal du membre', max_length=20),
        ),
    ]
