# Generated by Django 5.0.6 on 2026-08-01 22:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_date_naissance_user_personne_a_prevenir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='personne_a_prevenir',
        ),
        migrations.AlterField(
            model_name='user',
            name='membre_depuis',
            field=models.DateField(default=django.utils.timezone.now, help_text="Date d'entrée dans le groupe (ex: 2019)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonces', models.BooleanField(default=True)),
                ('cotisations', models.BooleanField(default=True)),
                ('sanctions', models.BooleanField(default=True)),
                ('programme', models.BooleanField(default=True)),
                ('servant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
    ]
