# Generated by Django 5.0.6 on 2026-07-31 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('type_messe', models.CharField(choices=[('MATINALE', 'Messe matinale'), ('SOIR', 'Messe du soir'), ('ADORATION', "Messe d'adoration"), ('AUTRE', 'Autre')], max_length=20)),
                ('lieu', models.CharField(blank=True, max_length=150)),
                ('servants', models.ManyToManyField(blank=True, related_name='messes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messe',
                'verbose_name_plural': 'Messes',
                'ordering': ['date', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='OrdreDuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordre du jour',
                'verbose_name_plural': 'Ordres du jour',
                'ordering': ['date'],
            },
        ),
    ]
