# Generated by Django 5.0.6 on 2026-08-03 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('enregistree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('ordre_du_jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='calendrier.ordredujour')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-ordre_du_jour__date'],
                'unique_together': {('ordre_du_jour', 'servant')},
            },
        ),
    ]
