# Generated by Django 5.0.6 on 2026-08-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0002_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='statut',
            field=models.CharField(choices=[('PRESENT', 'Présent'), ('RETARD', 'En retard'), ('PERMISSION', 'Permissionné'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='presence',
            name='present',
            field=models.BooleanField(default=True),
        ),
    ]
