# Generated by Django 5.0.6 on 2026-08-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0003_presence_statut_alter_presence_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordredujour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]