# Generated by Django 5.0.6 on 2026-08-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0004_ordredujour_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messe',
            name='nom_personnalise',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
