# Generated by Django 5.0.6 on 2026-08-09 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_saisi', models.CharField(blank=True, help_text="Utile si la connexion a échoué et qu'on n'a pas pu résoudre l'utilisateur.", max_length=50)),
                ('reussie', models.BooleanField(default=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connexion',
                'verbose_name_plural': 'Journal des connexions',
                'ordering': ['-date_connexion'],
            },
        ),
    ]
