# Generated by Django 5.0.6 on 2026-08-10 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Code technique de l'action, par exemple PROFILE_UPDATED.", max_length=100)),
                ('categorie', models.CharField(choices=[('AUTHENTICATION', 'Authentification'), ('ACCOUNT', 'Compte'), ('MEMBERS', 'Membres'), ('FINANCE', 'Trésorerie'), ('DISCIPLINE', 'Discipline'), ('CALENDAR', 'Calendrier'), ('ANNOUNCEMENT', 'Annonces'), ('SYSTEM', 'Système')], default='SYSTEM', max_length=30)),
                ('description', models.TextField(help_text="Description lisible de l'action.")),
                ('resultat', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILURE', 'Échec'), ('WARNING', 'Avertissement')], default='SUCCESS', max_length=20)),
                ('cible_type', models.CharField(blank=True, help_text='Type de ressource concernée, par exemple USER ou COTISATION.', max_length=50)),
                ('cible_id', models.CharField(blank=True, help_text='Identifiant de la ressource concernée.', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Informations supplémentaires liées à l'action.")),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Navigateur ou appareil utilisé.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Journal des activités',
                'ordering': ['-date_creation'],
            },
        ),
    ]
