# Generated by Django 5.0.6 on 2026-08-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0002_journalactivite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(help_text="Code technique de l'action. Exemple : PROFILE_UPDATED.", max_length=100),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='cible_type',
            field=models.CharField(blank=True, help_text='Type de ressource concernée. Exemple : USER, COTISATION.', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalconnexion',
            name='matricule_saisi',
            field=models.CharField(blank=True, help_text='Matricule saisi lors de la tentative de connexion.', max_length=50),
        ),
    ]
