# Generated by Django 5.0.6 on 2026-07-31 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(choices=[('AVERTISSEMENT', 'Avertissement'), ('AMENDE', 'Amende'), ('SUSPENSION', 'Suspension temporaire'), ('MISE_A_PIED', 'Mise à pied'), ('AUTRE', 'Autre')], max_length=20)),
                ('motif', models.TextField()),
                ('date_decision', models.DateField()),
                ('duree_jours', models.PositiveIntegerField(blank=True, help_text='Pour une suspension', null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text='Pour une amende', max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('LEVEE', 'Levée'), ('PURGEE', 'Purgée')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decidee_par', models.ForeignKey(blank=True, help_text="Le responsable disciplinaire à l'origine de la décision", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_decidees', to=settings.AUTH_USER_MODEL)),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'ordering': ['-date_decision'],
            },
        ),
    ]
