# Generated by Django 5.0.6 on 2026-08-05 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_caisse_inities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmationMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('DECLINE', 'Décliné')], default='EN_ATTENTE', max_length=10)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='caisse.mouvementcaisse')),
            ],
            options={
                'verbose_name': 'Confirmation de mouvement',
                'verbose_name_plural': 'Confirmations de mouvement',
                'unique_together': {('mouvement', 'membre')},
            },
        ),
    ]