# Generated by Django 5.0.6 on 2026-07-31 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('mois', models.PositiveSmallIntegerField(help_text='1 à 12')),
                ('numero_semaine', models.PositiveSmallIntegerField(help_text='1 à 5')),
                ('date_debut_semaine', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('statut', models.CharField(choices=[('PAYE', 'Payé'), ('IMPAYE', 'Impayé')], default='IMPAYE', max_length=10)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('enregistree_par', models.ForeignKey(blank=True, help_text='Le trésorier ayant enregistré le paiement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-annee', '-mois', 'numero_semaine'],
                'unique_together': {('servant', 'annee', 'mois', 'numero_semaine')},
            },
        ),
    ]
