# Generated by Django 5.0.6 on 2026-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
        ),
    ]
