# Generated by Django 5.0.6 on 2026-08-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0002_alter_cotisation_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
