# Generated by Django 5.0.6 on 2026-07-31 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=150)),
                ('contenu', models.TextField()),
                ('portee', models.CharField(choices=[('GENERALE', 'Générale'), ('CIBLEE', 'Pour toi')], default='GENERALE', max_length=10)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(blank=True, help_text='Renseigné uniquement si portee = CIBLEE', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces_recues', to=settings.AUTH_USER_MODEL)),
                ('publiee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_publiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_publication'],
            },
        ),
    ]
