# Generated by Django 5.0.6 on 2026-08-19 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='destinataire',
        ),
        migrations.AddField(
            model_name='annonce',
            name='destinataires',
            field=models.ManyToManyField(blank=True, help_text='Renseigné uniquement si portee = CIBLEE', related_name='annonces_recues', to=settings.AUTH_USER_MODEL),
        ),
    ]
